# Config File

# Site Settings
title: SPO600 Blog
email: your-email@example.com
description: "A blog for SPO600 class"
baseurl: "/spo600"
url: "https://cvvpk.github.io"
github_username: cvvpk

# Build settings
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/

# Additional config

paginate: 5
paginate_path: "page:num"
sass:
    style: compressed # Style compression
permalink: pretty # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
collections:
    posts:
        title: Blog # Needed for Siteleaf
        output: true
        description: "A blog for SPO600 class"
logo: "/assets/logo.png" # Site logo
